apiVersion: v2
name: simple-web
description: A Helm chart for deploying a web application
type: application
version: 0.5.0
appVersion: "1.0.0"
keywords:
  - web
  - simple
home: https://github.com/garrygerber/simple-web
sources:
  - https://github.com/garrygerber/simple-web
maintainers:
  - name: Garry Gerber
    email: garry@garrygerber.com
