# Default values for simple-web Helm chart

# Enable or disable the deployment
enabled: true

# Number of replicas for the deployment
replicaCount: 3

# Container image configuration
image:
  registry: acrinterview.azurecr.io
  repository: simple-web
  tag: latest
  pullPolicy: IfNotPresent

# Override the chart name
nameOverride: ""
# Override the full name of the chart
fullnameOverride: ""

# Service configuration
service:
  enabled: true
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP

# Container configuration
container:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  ports:
    - name: http
      containerPort: 80
      protocol: TCP

# ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod security context
podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 3000
  # fsGroup: 2000
  # seccompProfile:
  #   type: RuntimeDefault

# Container security context
containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #     - ALL
  # readOnlyRootFilesystem: true

# Image pull secrets for private registries
imagePullSecrets: {}

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  tls: {}
  hosts:
    - host: garry.acrinterview.com
      http:
        paths:
          - path: /garry
            pathType: Prefix
            backend:
              service:
                name: "{{ include \"simple-web.fullname\" . }}"
                port: 
                  number: 80

# Network policy configuration
networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0

# Node selector for pod scheduling
nodeSelector: {}

# Tolerations for pod scheduling
tolerations: []

# Affinity rules for pod scheduling
affinity: {}
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #         - key: app.kubernetes.io/name
  #           operator: In
  #           values:
  #           - simple-web
  #         - key: app.kubernetes.io/instance
  #           operator: In
  #           values:
  #           - "{{ .Release.Name }}"
  #         - key: app.kubernetes.io/tag
  #           operator: In
  #           values:
  #           - "{{ default .Chart.AppVersion .Values.image.tag }}"
  #       topologyKey: "kubernetes.io/hostname"

# Priority class name for pod scheduling
priorityClassName: ""

# Pod annotations
podAnnotations: {}

# Liveness probe configuration
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

# Readiness probe configuration
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

# KEDA autoscaler configuration
kedaScaler:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: 50
    - type: memory
      metadata:
        type: Utilization
        value: 50
    - type: cron
      metadata:
        timezone: "IDT"
        start: "0 8 * * *"
        end: "0 12 * * *"
        desiredReplicas: "3"

# Pod Disruption Budget configuration
podDisruptionBudget:
  enabled: false
  maxUnavailable: 1

dummy: "dummy2"