enabled: true
replicaCount: 3
image:
  registry: acrinterview.azurecr.io
  repository: simple-web
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

container:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  ports:
    - name: http
      containerPort: 80
      protocol: TCP

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

imagePullSecrets: {}


nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - simple-web
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - "{{ .Release.Name }}"
          - key: app.kubernetes.io/tag
            operator: In
            values:
            - "{{ default .Chart.AppVersion .Values.image.tag }}"
        topologyKey: "kubernetes.io/hostname"

priorityClassName: ""

podAnnotations: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

