enabled: true
replicaCount: 3
image:
  registry: acrinterview.azurecr.io
  repository: simple-web
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  enabled: true
  versioned: true
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP

container:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  ports:
    - name: http
      containerPort: 80
      protocol: TCP

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 3000
  # fsGroup: 2000
  # seccompProfile:
  #   type: RuntimeDefault

containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #     - ALL
  # readOnlyRootFilesystem: true

imagePullSecrets: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  tls: {}
  hosts:
    - host: garry.acrinterview.com
      http:
        paths:
          - path: /garry
            pathType: Prefix
            backend:
              service:
                name: "{{ include \"simple-web.versionedName\" . }}"
                port: 
                  number: 80

networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0


nodeSelector: {}

tolerations: []

affinity: {}
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #         - key: app.kubernetes.io/name
  #           operator: In
  #           values:
  #           - simple-web
  #         - key: app.kubernetes.io/instance
  #           operator: In
  #           values:
  #           - "{{ .Release.Name }}"
  #         - key: app.kubernetes.io/tag
  #           operator: In
  #           values:
  #           - "{{ default .Chart.AppVersion .Values.image.tag }}"
  #       topologyKey: "kubernetes.io/hostname"

priorityClassName: ""

podAnnotations: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

kedaScaler:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: 50
    - type: memory
      metadata:
        type: Utilization
        value: 50
    - type: cron
      metadata:
        timezone: "IDT"
        start: "0 8 * * *"
        end: "0 12 * * *"
        desiredReplicas: "3"

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1