{{- if (index .Values "podDisruptionBudget" "enabled") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "simple-web.versionedName" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
{{- with (index .Values "podDisruptionBudget") }}
  {{- with .minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "simple-web.selectorLabels" . | nindent 6 }}
{{- end }}