# Kubernetes ServiceAccount
{{- if (index .Values "serviceAccount" "create") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-web.serviceAccountName" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
  # ServiceAccount annotations
  {{- with (index .Values "serviceAccount" "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}