name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      chart:
        description: 'Chart to release (leave empty to release all)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install Helm
        uses: azure/setup-helm@v3

