name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      chart:
        description: 'Chart to release (leave empty to release all)'
        required: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.get-charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed charts
        id: get-charts
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -z "${{ github.event.inputs.chart }}" ]; then
              charts=$(ls -d charts/* | sed 's|charts/||' | jq -R -s -c 'split("\n")[:-1]')
            else
              charts="[\"${{ github.event.inputs.chart }}\"]"
            fi
          else
            changed_charts=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^charts/' | cut -d/ -f2 | sort -u)
            charts=$(echo "$changed_charts" | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "charts=$charts" >> $GITHUB_OUTPUT

  release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        chart: ${{fromJson(needs.prepare.outputs.charts)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run helm lint
        run: |
          helm lint ./charts/${{ matrix.chart }}

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './charts/${{ matrix.chart }}/Chart.yaml'
          version-path: 'version'
          output-file: './charts/${{ matrix.chart }}/CHANGELOG.md'
          tag-prefix: '${{ matrix.chart }}-v'
          create-summary: 'true'
          skip-git-pull: 'true'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts


