# GitHub Actions workflow for releasing Helm charts
name: Release Chart

# Trigger on pushes to main branch or manual workflow dispatch
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      chart:
        description: 'Chart to release (leave empty to release all)'
        required: false

# Permissions required for the workflow
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Job to prepare the list of charts to be released
  prepare:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.get-charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed charts
        id: get-charts
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -z "${{ github.event.inputs.chart }}" ]; then
              charts=$(ls -d charts/* | sed 's|charts/||' | jq -R -s -c 'split("\n")[:-1]')
            else
              charts="[\"${{ github.event.inputs.chart }}\"]"
            fi
          else
            changed_charts=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^charts/' | cut -d/ -f2 | sort -u)
            charts=$(echo "$changed_charts" | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "charts=$charts" >> $GITHUB_OUTPUT

  # Job to release the charts
  release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        chart: ${{fromJson(needs.prepare.outputs.charts)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install chart-releaser
        run: |
          curl -L https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz | tar xzf -
          sudo mv cr /usr/local/bin/cr

      - name: Run helm lint
        run: |
          helm lint ./charts/${{ matrix.chart }}

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './charts/${{ matrix.chart }}/Chart.yaml'
          version-path: 'version'
          output-file: './charts/${{ matrix.chart }}/CHANGELOG.md'
          tag-prefix: '${{ matrix.chart }}-v'
          create-summary: 'true'
          skip-git-pull: 'true'

      - name: Package and Release Chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          # Package the chart
          helm package ./charts/${{ matrix.chart }} -d .cr-release-packages

          # Upload the packaged chart
          cr upload -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} --skip-existing

      - name: Update Helm chart index
        run: |
          # Update the index
          cr index -i ./index.yaml -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }}

          git add index.yaml
          git commit index.yaml -m "chore: Update Helm chart index for ${{ matrix.chart }}"
          git push